# This rule is not used by the project op-sdk-scaffold itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to costmanagement-service-cfg.openshift.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: op-sdk-scaffold
    app.kubernetes.io/managed-by: kustomize
  name: costmanagementserviceconfig-viewer-role
rules:
- apiGroups:
  - costmanagement-service-cfg.openshift.io
  resources:
  - costmanagementserviceconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - costmanagement-service-cfg.openshift.io
  resources:
  - costmanagementserviceconfigs/status
  verbs:
  - get
