---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - service.costmanagement.openshift.io
  resources:
  - costmanagementserviceconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - service.costmanagement.openshift.io
  resources:
  - costmanagementserviceconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - service.costmanagement.openshift.io
  resources:
  - costmanagementserviceconfigs/status
  verbs:
  - get
  - patch
  - update
